name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - run: go mod download
        name: Cache gomod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          args: --timeout 600s
          only-new-issues: false
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run coverage
        run: make test-cover

      - name: Run Unit Test
        run: make test-unit

      - name: Run Integration Test
        run: make test-integration
